//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstateSet_Apartment
    {
        public double TotalArea { get; set; }
        public int Rooms { get; set; }
        public int Floor { get; set; }
        public int Id { get; set; }
    
        public virtual RealEstateSet RealEstateSet { get; set; }
    }
}
