//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplySet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplySet()
        {
            this.DealSets = new HashSet<DealSet>();
        }
    
        public int Id { get; set; }
        public long Price { get; set; }
        public Nullable<int> AgentId { get; set; }
        public int ClientId { get; set; }
        public int RealEstateId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealSet> DealSets { get; set; }
        public virtual PersonSet_Agent PersonSet_Agent { get; set; }
        public virtual PersonSet_Client PersonSet_Client { get; set; }
        public virtual RealEstateSet RealEstateSet { get; set; }
    }
}
